services:
  budget-app:
    build:
      context: .
      # args:
      #   BUILD_MEMORY_MB: 1024
    ports:
      - "3000:3001"
    volumes:
      - ./data:/app/data
    environment:
      - DATA_DIR=/app/data
    restart: unless-stopped
